import { LeaveBalance, LeaveRequest } from "../types";

export const INITIAL_LEAVE_BALANCES: LeaveBalance[] = [
  { leaveType: "Casual Leave", remainingDays: 8, annualQuota: 12 },
  { leaveType: "Sick Leave", remainingDays: 6, annualQuota: 10 },
  { leaveType: "Earned Leave", remainingDays: 10, annualQuota: 14 },
  { leaveType: "Festival Leave", remainingDays: 2, annualQuota: 2 },
];

export const MOCK_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: "LV-9901",
    employeeId: "EMP-1002",
    employeeName: "Tanjila Akter",
    role: "Accountant",
    branchName: "Main Branch",
    leaveType: "Casual Leave",
    startDate: "2026-07-30",
    endDate: "2026-07-31",
    totalDays: 2,
    appliedDate: "2026-07-28",
    reason: "Attending family wedding ceremony in Chittagong.",
    status: "pending",
    remainingBalancePreview: 8,
  },
  {
    id: "LV-9902",
    employeeId: "EMP-1003",
    employeeName: "Abul Kalam",
    role: "Sales Associate",
    branchName: "Mirpur Branch",
    leaveType: "Sick Leave",
    startDate: "2026-07-29",
    endDate: "2026-07-29",
    totalDays: 1,
    appliedDate: "2026-07-28",
    reason: "High fever and flu. Doctor advised 1 day rest.",
    status: "pending",
    remainingBalancePreview: 6,
  },
  {
    id: "LV-9903",
    employeeId: "EMP-1001",
    employeeName: "Kazi Shohel",
    avatarUrl: "/avatars/shohel.jpg",
    role: "Manager",
    branchName: "Main Branch",
    leaveType: "Casual Leave",
    startDate: "2026-06-10",
    endDate: "2026-06-11",
    totalDays: 2,
    appliedDate: "2026-06-05",
    reason: "Family event in hometown.",
    status: "approved",
    managerNote: "Approved by HR Director",
    reviewedBy: "HR Director",
    reviewedAt: "2026-06-06",
  },
  {
    id: "LV-9904",
    employeeId: "EMP-1004",
    employeeName: "Rafiqul Islam",
    role: "Store Keeper",
    branchName: "Gulshan Branch",
    leaveType: "Earned Leave",
    startDate: "2026-05-15",
    endDate: "2026-05-20",
    totalDays: 5,
    appliedDate: "2026-05-01",
    reason: "Personal vacation.",
    status: "rejected",
    managerNote: "Insufficient staff coverage during stock audit.",
    reviewedBy: "Kazi Shohel",
    reviewedAt: "2026-05-02",
  },
];
