import { PayrollRun, Payslip, SalaryStructure, BonusPayment } from "../types";

export const MOCK_PAYROLL_RUNS: PayrollRun[] = [
  {
    id: "PR-2026-07",
    periodName: "July 2026",
    branchName: "Main Branch",
    employeeCount: 4,
    totalGross: 510000,
    totalDeductions: 28000,
    totalNetPayroll: 482000,
    status: "completed",
    createdBy: "Anisur Rahman (Accountant)",
    createdDate: "2026-07-28",
    financeTransactionId: "TXN-FIN-9981",
    items: [
      {
        id: "item-1",
        employeeId: "EMP-1001",
        employeeName: "Kazi Shohel",
        role: "Manager",
        branchName: "Main Branch",
        basicSalary: 45000,
        allowances: 20000,
        overtimePay: 0,
        lateDeduction: 0,
        leaveDeduction: 2500,
        otherAdjustments: 0,
        netSalary: 62500,
        paymentStatus: "paid",
        paymentMethod: "Bank",
        paidDate: "2026-07-28",
      },
      {
        id: "item-2",
        employeeId: "EMP-1002",
        employeeName: "Tanjila Akter",
        role: "Accountant",
        branchName: "Main Branch",
        basicSalary: 35000,
        allowances: 10000,
        overtimePay: 0,
        lateDeduction: 0,
        leaveDeduction: 0,
        otherAdjustments: 0,
        netSalary: 45000,
        paymentStatus: "paid",
        paymentMethod: "Bank",
        paidDate: "2026-07-28",
      },
      {
        id: "item-3",
        employeeId: "EMP-1003",
        employeeName: "Abul Kalam",
        role: "Sales Associate",
        branchName: "Mirpur Branch",
        basicSalary: 18000,
        allowances: 5000,
        overtimePay: 1200,
        lateDeduction: 500,
        leaveDeduction: 0,
        otherAdjustments: 0,
        netSalary: 23700,
        paymentStatus: "pending",
        paymentMethod: "bKash",
      },
      {
        id: "item-4",
        employeeId: "EMP-1004",
        employeeName: "Rafiqul Islam",
        role: "Store Keeper",
        branchName: "Gulshan Branch",
        basicSalary: 20000,
        allowances: 0,
        overtimePay: 0,
        lateDeduction: 0,
        leaveDeduction: 0,
        otherAdjustments: 0,
        netSalary: 20000,
        paymentStatus: "pending",
        paymentMethod: "Cash",
      },
    ],
  },
];

export const MOCK_PAYSLIPS: Payslip[] = [
  {
    id: "PS-1001",
    employeeId: "EMP-1001",
    employeeName: "Kazi Shohel",
    role: "Manager",
    branchName: "Main Branch",
    monthYear: "July 2026",
    basicSalary: 45000,
    allowancesBreakdown: [
      { name: "House Rent Allowance", amount: 15000 },
      { name: "Conveyance Allowance", amount: 5000 },
    ],
    deductionsBreakdown: [
      { name: "Provident Fund Deduction", amount: 2500 },
    ],
    netPaid: 62500,
    paymentStatus: "paid",
    issueDate: "2026-07-28",
    paymentMethod: "Bank",
  },
  {
    id: "PS-1002",
    employeeId: "EMP-1002",
    employeeName: "Tanjila Akter",
    role: "Accountant",
    branchName: "Main Branch",
    monthYear: "July 2026",
    basicSalary: 35000,
    allowancesBreakdown: [
      { name: "House Rent Allowance", amount: 10000 },
    ],
    deductionsBreakdown: [],
    netPaid: 45000,
    paymentStatus: "paid",
    issueDate: "2026-07-28",
    paymentMethod: "Bank",
  },
];

export const MOCK_SALARY_STRUCTURES: SalaryStructure[] = [
  {
    id: "struct-1",
    employeeId: "EMP-1001",
    employeeName: "Kazi Shohel",
    role: "Manager",
    branchName: "Main Branch",
    basicSalary: 45000,
    allowances: [
      { id: "al-1", name: "House Rent", amount: 15000, type: "allowance" },
      { id: "al-2", name: "Conveyance", amount: 5000, type: "allowance" },
    ],
    deductions: [
      { id: "de-1", name: "Provident Fund", amount: 2500, type: "deduction" },
    ],
    grossSalary: 65000,
    netSalary: 62500,
  },
];

export const MOCK_BONUS_PAYMENTS: BonusPayment[] = [
  {
    id: "bon-1",
    bonusType: "Eid Bonus",
    title: "Eid-ul-Adha Festival Bonus 2026",
    branchName: "Main Branch",
    employeeCount: 12,
    totalBonusAmount: 240000,
    disbursedDate: "2026-06-15",
    status: "disbursed",
  },
];
