// Hello Khata OS - Roles & Permissions Mock Data & Registry
// হ্যালো খাতা - রোল ও পারমিশন রেজিস্ট্রি ও মক ডেটা

import type {
  ERPModuleDefinition,
  PermissionAction,
  BaseRoleDefinition,
  UserAccessProfile,
  AccessAuditEntry,
  PermissionModuleItem,
} from './types';

// ─── DEFAULT PERMISSION MODULES SCHEMA (FROM SETTINGS API) ───────────────────

export const DEFAULT_PERMISSION_MODULES: PermissionModuleItem[] = [
  {
    module: 'sales',
    label: 'Sales',
    labelBn: 'বিক্রয়',
    actions: ['view', 'create', 'edit', 'delete'],
  },
  {
    module: 'purchases',
    label: 'Purchases',
    labelBn: 'ক্রয়',
    actions: ['view', 'create', 'edit', 'delete'],
  },
  {
    module: 'inventory',
    label: 'Inventory',
    labelBn: 'ইনভেন্টরি',
    actions: ['view', 'create', 'edit', 'delete'],
  },
  {
    module: 'parties',
    label: 'Parties',
    labelBn: 'পক্ষসমূহ',
    actions: ['view', 'create', 'edit', 'delete'],
  },
  {
    module: 'expenses',
    label: 'Expenses',
    labelBn: 'ব্যয়',
    actions: ['view', 'create', 'edit', 'delete'],
  },
  {
    module: 'incomes',
    label: 'Incomes',
    labelBn: 'আয়',
    actions: ['view', 'create', 'edit', 'delete'],
  },
  {
    module: 'quotations',
    label: 'Quotations',
    labelBn: 'কোটেশন',
    actions: ['view', 'create', 'edit', 'delete'],
  },
  {
    module: 'reports',
    label: 'Reports',
    labelBn: 'প্রতিবেদন',
    actions: ['view'],
  },
  {
    module: 'dashboard',
    label: 'Dashboard',
    labelBn: 'ড্যাশবোর্ড',
    actions: ['view'],
  },
  {
    module: 'settings',
    label: 'Settings',
    labelBn: 'সেটিংস',
    actions: ['view', 'edit'],
  },
  {
    module: 'staff',
    label: 'Staff',
    labelBn: 'কর্মী',
    actions: ['view', 'create', 'edit', 'delete'],
  },
];

// ─── COMPLETE ERP MODULE PERMISSION REGISTRY (10 CORE MODULES) ───────────────

export const ERP_MODULES: ERPModuleDefinition[] = [
  {
    id: 'mod_dashboard',
    code: 'DASHBOARD',
    name: 'Dashboard & Analytics',
    nameBn: 'ড্যাশবোর্ড ও বিশ্লেষণ',
    description: 'Executive KPIs, revenue metrics, branch performance, and business insights.',
    descriptionBn: 'ব্যবসায়িক কেপিআই, রাজস্ব পরিমাপ, শাখা কর্মক্ষমতা এবং গুরুত্বপূর্ণ পরিসংখ্যান।',
    iconName: 'LayoutGrid',
    readOnlyPermissionIds: ['dash_view_overview', 'dash_view_branch_kpi'],
    standardPermissionIds: ['dash_view_overview', 'dash_view_branch_kpi', 'dash_export_kpi'],
    permissions: [
      { id: 'dash_view_overview', code: 'DASH_VIEW_OVERVIEW', name: 'View Dashboard', nameBn: 'ড্যাশবোর্ড দেখুন', description: 'Access standard dashboard charts & summaries', category: 'view' },
      { id: 'dash_view_summary', code: 'DASH_VIEW_SUMMARY', name: 'View Business Summary', nameBn: 'ব্যবসায়িক সারাংশ দেখুন', description: 'View net profit, margins, and sales revenue', category: 'view', isSensitive: true },
      { id: 'dash_view_branch_kpi', code: 'DASH_VIEW_BRANCH_KPI', name: 'View Branch Analytics', nameBn: 'শাখার অ্যানালিটিক্স দেখুন', description: 'Compare multi-branch performance metrics', category: 'view' },
      { id: 'dash_export_kpi', code: 'DASH_EXPORT_KPI', name: 'Export Dashboard Data', nameBn: 'ড্যাশবোর্ড ডেটা এক্সপোর্ট', description: 'Export visual reports as PDF or spreadsheet', category: 'export' },
    ],
  },
  {
    id: 'mod_sales',
    code: 'SALES_POS',
    name: 'Sales & POS',
    nameBn: 'বিক্রয় ও পিওএস',
    description: 'Point of Sale, invoices, billing, cash registers, returns, and quotations.',
    descriptionBn: 'পিওএস কাউন্টার বিলিং, ইনভয়েস তৈরি, ক্যাশ রেজিস্টার ও রিটার্ন ব্যবস্থাপনা।',
    iconName: 'ShoppingCart',
    readOnlyPermissionIds: ['sales_view', 'sales_view_history'],
    standardPermissionIds: ['sales_view', 'sales_create', 'sales_edit', 'sales_process_return', 'sales_view_history'],
    permissions: [
      { id: 'sales_view', code: 'SALES_VIEW', name: 'View Sales', nameBn: 'বিক্রয় তালিকা দেখুন', description: 'View sales invoices, receipts, and order logs', category: 'view' },
      { id: 'sales_create', code: 'SALES_CREATE', name: 'Create Sale / POS Billing', nameBn: 'নতুন বিক্রয় তৈরি করুন', description: 'Generate POS receipts and standard sales orders', category: 'create', dependsOn: ['sales_view'] },
      { id: 'sales_edit', code: 'SALES_EDIT', name: 'Edit Sale Invoices', nameBn: 'বিক্রয় ইনভয়েস সম্পাদনা', description: 'Modify line items, quantities, or customer details', category: 'edit', dependsOn: ['sales_view'] },
      { id: 'sales_delete', code: 'SALES_DELETE', name: 'Delete / Void Sale', nameBn: 'বিক্রয় বাতিল বা মুছে ফেলুন', description: 'Cancel existing sale invoices and reverse ledger', category: 'delete', isSensitive: true, dependsOn: ['sales_view'] },
      { id: 'sales_apply_discount', code: 'SALES_APPLY_DISCOUNT', name: 'Apply Discounts', nameBn: 'ডিসকাউন্ট প্রয়োগ করুন', description: 'Grant custom discounts at POS checkout', category: 'special' },
      { id: 'sales_price_override', code: 'SALES_PRICE_OVERRIDE', name: 'Override Unit Prices', nameBn: 'মূল্য পরিবর্তন করুন', description: 'Manually alter selling prices from retail default', category: 'special', isSensitive: true },
      { id: 'sales_process_return', code: 'SALES_PROCESS_RETURN', name: 'Process Sales Returns', nameBn: 'বিক্রয় রিটার্ন প্রসেস', description: 'Accept customer product returns and issue refunds', category: 'edit', dependsOn: ['sales_view'] },
      { id: 'sales_view_history', code: 'SALES_VIEW_HISTORY', name: 'View Sales History', nameBn: 'বিক্রয় ইতিহাস দেখুন', description: 'Inspect audit trail of modified orders', category: 'view' },
      { id: 'sales_export', code: 'SALES_EXPORT', name: 'Export Sales Data', nameBn: 'বিক্রয় ডেটা এক্সপোর্ট', description: 'Download CSV and Excel files of all sales invoices', category: 'export', dependsOn: ['sales_view'] },
      { id: 'sales_manage_pos', code: 'SALES_MANAGE_POS', name: 'Manage POS Register', nameBn: 'পিওএস ক্যাশ ড্রয়ার নিয়ন্ত্রণ', description: 'Open/close day register, cash-in, and cash-out', category: 'special' },
    ],
  },
  {
    id: 'mod_purchases',
    code: 'PURCHASES',
    name: 'Purchases & Suppliers',
    nameBn: 'ক্রয় ও সরবরাহকারী',
    description: 'Supplier orders, goods received notes (GRN), purchase returns, and payables.',
    descriptionBn: 'সরবরাহকারী ক্রয় আদেশ, পণ্য গ্রহণ (GRN), ক্রয় রিটার্ন এবং বকেয়া বিল।',
    iconName: 'Truck',
    readOnlyPermissionIds: ['pur_view', 'pur_view_history'],
    standardPermissionIds: ['pur_view', 'pur_create', 'pur_edit', 'pur_process_return', 'pur_view_history'],
    permissions: [
      { id: 'pur_view', code: 'PUR_VIEW', name: 'View Purchases', nameBn: 'ক্রয় তালিকা দেখুন', description: 'Inspect all purchase orders and vendor bills', category: 'view' },
      { id: 'pur_create', code: 'PUR_CREATE', name: 'Create Purchase Order', nameBn: 'নতুন ক্রয় আদেশ তৈরি', description: 'Issue POs and record goods received into stock', category: 'create', dependsOn: ['pur_view'] },
      { id: 'pur_edit', code: 'PUR_EDIT', name: 'Edit Purchase Invoices', nameBn: 'ক্রয় বিল সম্পাদনা', description: 'Update supplier bills, unit costs, and tax entries', category: 'edit', dependsOn: ['pur_view'] },
      { id: 'pur_delete', code: 'PUR_DELETE', name: 'Delete Purchase Records', nameBn: 'ক্রয় রেকর্ড মুছে ফেলুন', description: 'Remove purchase orders and reverse supplier credits', category: 'delete', isSensitive: true, dependsOn: ['pur_view'] },
      { id: 'pur_approve', code: 'PUR_APPROVE', name: 'Approve High-Value POs', nameBn: 'উচ্চ মূল্যের ক্রয় অনুমোদন', description: 'Authorize purchasing orders above preset limits', category: 'approve', isSensitive: true, dependsOn: ['pur_view'] },
      { id: 'pur_process_return', code: 'PUR_PROCESS_RETURN', name: 'Process Purchase Returns', nameBn: 'ক্রয় রিটার্ন প্রসেস', description: 'Return damaged or surplus items to vendor', category: 'edit', dependsOn: ['pur_view'] },
      { id: 'pur_view_history', code: 'PUR_VIEW_HISTORY', name: 'View Purchase History', nameBn: 'ক্রয় ইতিহাস দেখুন', description: 'View cost revision audit logs', category: 'view' },
      { id: 'pur_export', code: 'PUR_EXPORT', name: 'Export Purchase Data', nameBn: 'ক্রয় ডেটা এক্সপোর্ট', description: 'Export purchase bills and supplier ledgers', category: 'export', dependsOn: ['pur_view'] },
    ],
  },
  {
    id: 'mod_inventory',
    code: 'INVENTORY',
    name: 'Inventory & Warehouses',
    nameBn: 'ইনভেন্টরি ও ওয়্যারহাউস',
    description: 'Stock tracking, batches, FEFO expiry alerts, warehouse transfers, and adjustments.',
    descriptionBn: 'স্টক ট্র্যাকিং, ব্যাচ ও মেয়াদোত্তীর্ণ সতর্কতা, গুদাম স্থানান্তর ও সমন্বয়।',
    iconName: 'Package',
    readOnlyPermissionIds: ['inv_view', 'inv_view_alerts', 'inv_view_history'],
    standardPermissionIds: ['inv_view', 'inv_add_products', 'inv_edit_products', 'inv_transfer_stock', 'inv_view_alerts', 'inv_batches'],
    permissions: [
      { id: 'inv_view', code: 'INV_VIEW', name: 'View Inventory', nameBn: 'ইনভেন্টরি দেখুন', description: 'View item catalogue, stock counts, and valuation', category: 'view' },
      { id: 'inv_add_products', code: 'INV_ADD_PRODUCTS', name: 'Add Products', nameBn: 'নতুন পণ্য যোগ করুন', description: 'Create new SKU, barcodes, categories, and brands', category: 'create', dependsOn: ['inv_view'] },
      { id: 'inv_edit_products', code: 'INV_EDIT_PRODUCTS', name: 'Edit Products', nameBn: 'পণ্য সম্পাদনা করুন', description: 'Update product prices, specs, and reorder levels', category: 'edit', dependsOn: ['inv_view'] },
      { id: 'inv_delete_products', code: 'INV_DELETE_PRODUCTS', name: 'Delete Products', nameBn: 'পণ্য মুছে ফেলুন', description: 'Permanently remove inactive or obsolete items', category: 'delete', isSensitive: true, dependsOn: ['inv_view'] },
      { id: 'inv_adjust_stock', code: 'INV_ADJUST_STOCK', name: 'Adjust Stock / Write-Offs', nameBn: 'স্টক সমন্বয় ও অবচয়', description: 'Manually modify stock counts due to damage/theft', category: 'special', isSensitive: true, dependsOn: ['inv_view'] },
      { id: 'inv_transfer_stock', code: 'INV_TRANSFER_STOCK', name: 'Transfer Between Branches', nameBn: 'শাখা/গুদাম স্থানান্তর', description: 'Dispatch and receive internal stock transfer notes', category: 'edit', dependsOn: ['inv_view'] },
      { id: 'inv_manage_warehouses', code: 'INV_MANAGE_WAREHOUSES', name: 'Manage Warehouses & Racks', nameBn: 'ওয়্যারহাউস ব্যবস্থাপনা', description: 'Create and configure warehouse storage locations', category: 'special', isSensitive: true },
      { id: 'inv_view_alerts', code: 'INV_VIEW_ALERTS', name: 'View Low Stock & Expiry', nameBn: 'স্বল্প স্টক ও মেয়াদ সতর্কতা', description: 'Inspect real-time FEFO alerts and replenishment needs', category: 'view' },
      { id: 'inv_batches', code: 'INV_BATCHES', name: 'Manage Batches & Expiry', nameBn: 'ব্যাচ ও মেয়াদ পরিচালনা', description: 'Assign batch numbers, manufacturing dates, and lot tags', category: 'edit', dependsOn: ['inv_view'] },
      { id: 'inv_export', code: 'INV_EXPORT', name: 'Export Stock Reports', nameBn: 'স্টক রিপোর্ট এক্সপোর্ট', description: 'Export full stock ledger and valuation sheets', category: 'export', dependsOn: ['inv_view'] },
    ],
  },
  {
    id: 'mod_parties',
    code: 'PARTIES',
    name: 'Parties (Customers & Suppliers)',
    nameBn: 'পার্টি (গ্রাহক ও সরবরাহকারী)',
    description: 'CRM contacts, credit limits, khata ledgers, party balance statements, and phonebook.',
    descriptionBn: 'গ্রাহক ও সরবরাহকারী খাতা, বাকির সীমা, কন্টাক্ট ডিরেক্টরি এবং লেনদেন হিসেব।',
    iconName: 'Users',
    readOnlyPermissionIds: ['party_view_customers', 'party_view_suppliers', 'party_view_transactions'],
    standardPermissionIds: ['party_view_customers', 'party_view_suppliers', 'party_create_customer', 'party_edit_customer', 'party_create_supplier', 'party_view_transactions'],
    permissions: [
      { id: 'party_view_customers', code: 'PARTY_VIEW_CUSTOMERS', name: 'View Customers', nameBn: 'গ্রাহক তালিকা দেখুন', description: 'Access customer profiles and transaction totals', category: 'view' },
      { id: 'party_create_customer', code: 'PARTY_CREATE_CUSTOMER', name: 'Create Customer', nameBn: 'নতুন গ্রাহক তৈরি', description: 'Register new customers into the company ledger', category: 'create' },
      { id: 'party_edit_customer', code: 'PARTY_EDIT_CUSTOMER', name: 'Edit Customer', nameBn: 'গ্রাহক তথ্য সম্পাদনা', description: 'Update customer phone, address, and credit settings', category: 'edit', dependsOn: ['party_view_customers'] },
      { id: 'party_delete_customer', code: 'PARTY_DELETE_CUSTOMER', name: 'Delete Customer', nameBn: 'গ্রাহক মুছে ফেলুন', description: 'Remove customer accounts with zero balance', category: 'delete', isSensitive: true, dependsOn: ['party_view_customers'] },
      { id: 'party_view_suppliers', code: 'PARTY_VIEW_SUPPLIERS', name: 'View Suppliers', nameBn: 'সরবরাহকারী দেখুন', description: 'Inspect vendor list and payable ledger balances', category: 'view' },
      { id: 'party_create_supplier', code: 'PARTY_CREATE_SUPPLIER', name: 'Create Supplier', nameBn: 'নতুন সরবরাহকারী যোগ', description: 'Add new supplier company details and contacts', category: 'create' },
      { id: 'party_edit_supplier', code: 'PARTY_EDIT_SUPPLIER', name: 'Edit Supplier', nameBn: 'সরবরাহকারী সম্পাদনা', description: 'Modify vendor terms and payment addresses', category: 'edit', dependsOn: ['party_view_suppliers'] },
      { id: 'party_delete_supplier', code: 'PARTY_DELETE_SUPPLIER', name: 'Delete Supplier', nameBn: 'সরবরাহকারী মুছে ফেলুন', description: 'Remove vendor accounts from the system', category: 'delete', isSensitive: true, dependsOn: ['party_view_suppliers'] },
      { id: 'party_manage_credit_limits', code: 'PARTY_MANAGE_CREDIT_LIMITS', name: 'Manage Credit Limits', nameBn: 'বাকির সীমা (Credit Limit) নির্ধারণ', description: 'Set max allowed due amount for specific buyers', category: 'special', isSensitive: true },
      { id: 'party_view_transactions', code: 'PARTY_VIEW_TRANSACTIONS', name: 'View Party Ledgers', nameBn: 'পার্টি লেজার ও লেনদেন হিসেব', description: 'Review detailed chronological Khata balances', category: 'view' },
      { id: 'party_export', code: 'PARTY_EXPORT', name: 'Export Party Ledgers', nameBn: 'পার্টি ডেটা এক্সপোর্ট', description: 'Download party lists and customer khata summaries', category: 'export' },
    ],
  },
  {
    id: 'mod_finance',
    code: 'FINANCE',
    name: 'Finance & Accounts',
    nameBn: 'অর্থ ও হিসাববিজ্ঞান',
    description: 'Income, expenses, bank accounts, bKash/Nagad wallets, cash flow, and equity.',
    descriptionBn: 'আয়-ব্যয়, ব্যাংক ও মোবাইল ওয়ালেট (bKash/Nagad), ক্যাশ ফ্লো ও মালিকের মূলধন।',
    iconName: 'Landmark',
    readOnlyPermissionIds: ['fin_view_overview', 'fin_view_transactions', 'fin_view_reports'],
    standardPermissionIds: ['fin_view_overview', 'fin_view_transactions', 'fin_create_transactions', 'fin_manage_expenses', 'fin_manage_payments'],
    permissions: [
      { id: 'fin_view_overview', code: 'FIN_VIEW_OVERVIEW', name: 'View Financial Overview', nameBn: 'আর্থিক বিবরণী দেখুন', description: 'Access cash position, daily cash book, and summaries', category: 'view' },
      { id: 'fin_view_transactions', code: 'FIN_VIEW_TRANSACTIONS', name: 'View Transactions', nameBn: 'লেনদেন তালিকা দেখুন', description: 'Inspect all income and expense vouchers', category: 'view' },
      { id: 'fin_create_transactions', code: 'FIN_CREATE_TRANSACTIONS', name: 'Record Transactions', nameBn: 'নতুন লেনদেন এন্ট্রি', description: 'Create receipt and payment vouchers', category: 'create', dependsOn: ['fin_view_transactions'] },
      { id: 'fin_edit_transactions', code: 'FIN_EDIT_TRANSACTIONS', name: 'Edit Transactions', nameBn: 'লেনদেন সম্পাদনা', description: 'Modify voucher heads, amounts, or payment modes', category: 'edit', isSensitive: true, dependsOn: ['fin_view_transactions'] },
      { id: 'fin_delete_transactions', code: 'FIN_DELETE_TRANSACTIONS', name: 'Delete Transactions', nameBn: 'লেনদেন মুছে ফেলুন', description: 'Delete recorded vouchers and reverse ledger entries', category: 'delete', isSensitive: true, dependsOn: ['fin_view_transactions'] },
      { id: 'fin_manage_expenses', code: 'FIN_MANAGE_EXPENSES', name: 'Manage Expenses', nameBn: 'খরচ পরিচালনা', description: 'Create expense heads, petty cash vouchers, and bills', category: 'create' },
      { id: 'fin_manage_payments', code: 'FIN_MANAGE_PAYMENTS', name: 'Process Payments', nameBn: 'পেমেন্ট সম্পন্ন করুন', description: 'Disburse supplier settlements and vendor cheques', category: 'special' },
      { id: 'fin_manage_banks', code: 'FIN_MANAGE_BANKS', name: 'Manage Bank & Wallets', nameBn: 'ব্যাংক ও ওয়ালেট ব্যবস্থাপনা', description: 'Add/configure bank accounts and MFS gateway keys', category: 'special', isSensitive: true },
      { id: 'fin_manage_capital', code: 'FIN_MANAGE_CAPITAL', name: 'Manage Owner Capital', nameBn: 'মালিকের মূলধন ও উত্তোলন', description: 'Record owner equity injections and personal drawings', category: 'special', isSensitive: true },
      { id: 'fin_view_reports', code: 'FIN_VIEW_REPORTS', name: 'View Profit & Loss', nameBn: 'লাভ-ক্ষতি ও ব্যালেন্স শীট', description: 'View net profit statement and trial balance', category: 'view', isSensitive: true },
      { id: 'fin_export', code: 'FIN_EXPORT', name: 'Export Financial Data', nameBn: 'আর্থিক হিসাব এক্সপোর্ট', description: 'Export balance sheet, cash book, and tax summaries', category: 'export', isSensitive: true },
    ],
  },
  {
    id: 'mod_hrm',
    code: 'HRM',
    name: 'HRM & Payroll',
    nameBn: 'এইচআরএম ও বেতন',
    description: 'Employee profiles, biometric attendance, leave approvals, salary slips, and bonuses.',
    descriptionBn: 'কর্মী ব্যবস্থাপনা, উপস্থিতি, ছুটির আবেদন, বেতন শিট প্রস্তুত ও স্যালারি স্লিপ।',
    iconName: 'UserCog',
    readOnlyPermissionIds: ['hrm_view_employees', 'hrm_view_attendance'],
    standardPermissionIds: ['hrm_view_employees', 'hrm_add_employees', 'hrm_manage_attendance', 'hrm_manage_leave'],
    permissions: [
      { id: 'hrm_view_employees', code: 'HRM_VIEW_EMPLOYEES', name: 'View Employees', nameBn: 'কর্মী তালিকা দেখুন', description: 'View employee directory, contacts, and designations', category: 'view' },
      { id: 'hrm_add_employees', code: 'HRM_ADD_EMPLOYEES', name: 'Add New Employees', nameBn: 'নতুন কর্মী যোগ করুন', description: 'Onboard new staff, capture NID, and set department', category: 'create', dependsOn: ['hrm_view_employees'] },
      { id: 'hrm_edit_employees', code: 'HRM_EDIT_EMPLOYEES', name: 'Edit Employee Records', nameBn: 'কর্মী তথ্য সম্পাদনা', description: 'Update salary grade, designation, and branch allocation', category: 'edit', isSensitive: true, dependsOn: ['hrm_view_employees'] },
      { id: 'hrm_delete_employees', code: 'HRM_DELETE_EMPLOYEES', name: 'Terminate / Delete Staff', nameBn: 'কর্মী ছাঁটাই বা মুছে ফেলুন', description: 'Deactivate employee profile and remove system access', category: 'delete', isSensitive: true, dependsOn: ['hrm_view_employees'] },
      { id: 'hrm_manage_attendance', code: 'HRM_MANAGE_ATTENDANCE', name: 'Manage Attendance', nameBn: 'উপস্থিতি পরিচালনা', description: 'Record daily punch in/out and manual overrides', category: 'edit' },
      { id: 'hrm_manage_leave', code: 'HRM_MANAGE_LEAVE', name: 'Approve Leave Requests', nameBn: 'ছুটি মঞ্জুর ও বাতিল', description: 'Review and approve/reject staff leave applications', category: 'approve' },
      { id: 'hrm_manage_payroll', code: 'HRM_MANAGE_PAYROLL', name: 'Process Payroll & Salary', nameBn: 'বেতন শিট ও স্যালারি প্রদান', description: 'Calculate monthly salaries, deductions, and bonuses', category: 'special', isSensitive: true },
      { id: 'hrm_view_reports', code: 'HRM_VIEW_REPORTS', name: 'View HR Reports', nameBn: 'এইচআর রিপোর্ট দেখুন', description: 'Inspect attendance trends and overtime logs', category: 'view' },
      { id: 'hrm_export', code: 'HRM_EXPORT', name: 'Export Payroll & Staff Data', nameBn: 'এইচআর ডেটা এক্সপোর্ট', description: 'Download bank salary sheets and attendance logs', category: 'export', isSensitive: true },
    ],
  },
  {
    id: 'mod_reports',
    code: 'REPORTS',
    name: 'Reports & Intelligence',
    nameBn: 'রিপোর্ট ও বিশ্লেষণ',
    description: 'Comprehensive business reports, sales insights, inventory audits, and tax returns.',
    descriptionBn: 'সামগ্রিক ব্যবসায়িক রিপোর্ট, সেলস অ্যানালিটিক্স, ট্যাক্স/ভ্যাট হিসেব ও পিডিএফ ডাউনলোড।',
    iconName: 'FileSpreadsheet',
    readOnlyPermissionIds: ['rep_view_sales', 'rep_view_inventory'],
    standardPermissionIds: ['rep_view_sales', 'rep_view_purchase', 'rep_view_inventory', 'rep_download_pdf'],
    permissions: [
      { id: 'rep_view_sales', code: 'REP_VIEW_SALES', name: 'View Sales Reports', nameBn: 'বিক্রয় রিপোর্ট দেখুন', description: 'Daily, monthly, and yearly sales summaries', category: 'view' },
      { id: 'rep_view_purchase', code: 'REP_VIEW_PURCHASE', name: 'View Purchase Reports', nameBn: 'ক্রয় রিপোর্ট দেখুন', description: 'Vendor expenditure and procurement statistics', category: 'view' },
      { id: 'rep_view_inventory', code: 'REP_VIEW_INVENTORY', name: 'View Inventory Reports', nameBn: 'ইনভেন্টরি স্টক রিপোর্ট', description: 'Stock movement, slow-moving items, and stock audit', category: 'view' },
      { id: 'rep_view_financial', code: 'REP_VIEW_FINANCIAL', name: 'View Financial Audits', nameBn: 'আর্থিক অডিট রিপোর্ট', description: 'Cash flow statement, VAT ledger, and expense splits', category: 'view', isSensitive: true },
      { id: 'rep_view_hr', code: 'REP_VIEW_HR', name: 'View HR & Payroll Reports', nameBn: 'এইচআর ও বেতন রিপোর্ট', description: 'Salary disbursement logs and leave breakdown', category: 'view', isSensitive: true },
      { id: 'rep_export_excel', code: 'REP_EXPORT_EXCEL', name: 'Export Data to Excel/CSV', nameBn: 'এক্সেল বা সিএসভি এক্সপোর্ট', description: 'Download raw tabular datasets', category: 'export' },
      { id: 'rep_download_pdf', code: 'REP_DOWNLOAD_PDF', name: 'Download PDF Reports', nameBn: 'পিডিএফ রিপোর্ট ডাউনলোড', description: 'Generate formatted printable audit reports', category: 'export' },
    ],
  },
  {
    id: 'mod_quotations',
    code: 'QUOTATIONS',
    name: 'Quotations & Estimates',
    nameBn: 'কোটেশন ও প্রাক্কলন',
    description: 'Price proposals, project estimates, discount approvals, and sale conversion.',
    descriptionBn: 'দর প্রস্তাব, প্রকল্প ব্যয় প্রাক্কলন ও সরাসরি বিক্রয়ে রূপান্তর।',
    iconName: 'FileText',
    readOnlyPermissionIds: ['quote_view'],
    standardPermissionIds: ['quote_view', 'quote_create', 'quote_edit', 'quote_convert'],
    permissions: [
      { id: 'quote_view', code: 'QUOTE_VIEW', name: 'View Quotations', nameBn: 'কোটেশন তালিকা দেখুন', description: 'Inspect sent and draft price proposals', category: 'view' },
      { id: 'quote_create', code: 'QUOTE_CREATE', name: 'Create Quotation', nameBn: 'নতুন কোটেশন তৈরি', description: 'Draft estimates with terms and item pricing', category: 'create', dependsOn: ['quote_view'] },
      { id: 'quote_edit', code: 'QUOTE_EDIT', name: 'Edit Quotations', nameBn: 'কোটেশন সম্পাদনা', description: 'Modify quote quantities, prices, and validities', category: 'edit', dependsOn: ['quote_view'] },
      { id: 'quote_delete', code: 'QUOTE_DELETE', name: 'Delete Quotations', nameBn: 'কোটেশন মুছে ফেলুন', description: 'Discard expired or rejected quotations', category: 'delete', dependsOn: ['quote_view'] },
      { id: 'quote_approve', code: 'QUOTE_APPROVE', name: 'Approve Quotation', nameBn: 'কোটেশন অনুমোদন', description: 'Authorize formal proposal sent to client', category: 'approve' },
      { id: 'quote_convert', code: 'QUOTE_CONVERT', name: 'Convert Quotation to Sale', nameBn: 'কোটেশন থেকে সেল ইনভয়েস', description: 'Instantly convert approved estimate into sale invoice', category: 'create', dependsOn: ['quote_view', 'sales_create'] },
    ],
  },
  {
    id: 'mod_settings',
    code: 'SETTINGS',
    name: 'Settings & Administration',
    nameBn: 'সেটিংস ও প্রশাসন',
    description: 'Company profile, branches, warehouses, user accounts, and security audit logs.',
    descriptionBn: 'কোম্পানি প্রোফাইল, শাখা, ওয়্যারহাউস, ইউজার অ্যাক্সেস ও অডিট লগ।',
    iconName: 'Settings',
    readOnlyPermissionIds: ['set_view_profile'],
    standardPermissionIds: ['set_view_profile'],
    permissions: [
      { id: 'set_view_profile', code: 'SET_VIEW_PROFILE', name: 'View Business Settings', nameBn: 'ব্যবসার সেটিংস দেখুন', description: 'Inspect invoice templates and company info', category: 'view' },
      { id: 'set_manage_business', code: 'SET_MANAGE_BUSINESS', name: 'Manage Business Profile', nameBn: 'কোম্পানি তথ্য পরিবর্তন', description: 'Update trade licence, logo, VAT/BIN numbers, and address', category: 'special', isSensitive: true },
      { id: 'set_manage_users', code: 'SET_MANAGE_USERS', name: 'Manage User Accounts', nameBn: 'ব্যবহারকারী অ্যাকাউন্ট নিয়ন্ত্রণ', description: 'Create user logins, reset passwords, and lock accounts', category: 'special', isSensitive: true },
      { id: 'set_manage_roles', code: 'SET_MANAGE_ROLES', name: 'Manage Roles & Permissions', nameBn: 'ভূমিকা ও পারমিশন পরিবর্তন', description: 'Configure granular module permissions and overrides', category: 'special', isSensitive: true },
      { id: 'set_manage_branches', code: 'SET_MANAGE_BRANCHES', name: 'Manage Branches & Outlets', nameBn: 'শাখা ও আউটলেট যোগ/বাতিল', description: 'Open new retail stores and branch locations', category: 'special', isSensitive: true },
      { id: 'set_view_audit_logs', code: 'SET_VIEW_AUDIT_LOGS', name: 'View Security Audit Logs', nameBn: 'নিরাপত্তা অডিট লগ দেখুন', description: 'Review system-wide access and security audit trail', category: 'view', isSensitive: true },
      { id: 'set_manage_subscription', code: 'SET_MANAGE_SUBSCRIPTION', name: 'Manage Subscription & Plan', nameBn: 'সাবস্ক্রিপশন ও বিলিং', description: 'Upgrade package, renew subscription, and invoices', category: 'special', isSensitive: true },
    ],
  },
];

// Helper: Flatten all permission IDs
export const ALL_PERMISSION_IDS = ERP_MODULES.flatMap((m) => m.permissions.map((p) => p.id));
export const ALL_SENSITIVE_PERMISSION_IDS = ERP_MODULES.flatMap((m) =>
  m.permissions.filter((p) => p.isSensitive).map((p) => p.id)
);

// Map permission id to permission object
export const PERMISSION_BY_ID_MAP = new Map<string, PermissionAction>();
ERP_MODULES.forEach((m) => {
  m.permissions.forEach((p) => {
    PERMISSION_BY_ID_MAP.set(p.id, p);
  });
});

// Map permission id to module object
export const MODULE_BY_PERMISSION_ID_MAP = new Map<string, ERPModuleDefinition>();
ERP_MODULES.forEach((m) => {
  m.permissions.forEach((p) => {
    MODULE_BY_PERMISSION_ID_MAP.set(p.id, m);
  });
});

// ─── BASE ROLE DEFINITIONS (TEMPLATES & INHERITANCE) ─────────────────────────

export const INITIAL_BASE_ROLES: BaseRoleDefinition[] = [
  {
    id: 'role-owner',
    name: 'Owner / Super Admin',
    nameBn: 'মালিক / সুপার অ্যাডমিন',
    description: 'Full uninhibited system access across all branches, accounts, and administration.',
    descriptionBn: 'সকল শাখা, আর্থিক হিসাব ও নিরাপত্তা সেটিংসের পূর্ণ অ্যাক্সেস।',
    isSystemProtected: true,
    color: '#8b5cf6',
    defaultDataScope: 'entire_business',
    defaultBranchMode: 'all',
    permissionIds: ALL_PERMISSION_IDS,
  },
  {
    id: 'role-branch-manager',
    name: 'Branch Manager',
    nameBn: 'শাখা ব্যবস্থাপক',
    description: 'Full operational control over assigned branch(es) including Sales, Purchases, Stock, and Staff.',
    descriptionBn: 'নির্দিষ্ট শাখার বিক্রয়, ক্রয়, স্টক ও কর্মীদের সম্পূর্ণ পরিচালনা।',
    isSystemProtected: true,
    color: '#0ea5e9',
    defaultDataScope: 'assigned_branches',
    defaultBranchMode: 'selected',
    permissionIds: [
      'dash_view_overview', 'dash_view_branch_kpi', 'dash_export_kpi',
      'sales_view', 'sales_create', 'sales_edit', 'sales_apply_discount', 'sales_process_return', 'sales_view_history', 'sales_export', 'sales_manage_pos',
      'pur_view', 'pur_create', 'pur_edit', 'pur_approve', 'pur_process_return', 'pur_view_history', 'pur_export',
      'inv_view', 'inv_add_products', 'inv_edit_products', 'inv_adjust_stock', 'inv_transfer_stock', 'inv_view_alerts', 'inv_batches', 'inv_export',
      'party_view_customers', 'party_create_customer', 'party_edit_customer', 'party_view_suppliers', 'party_create_supplier', 'party_view_transactions', 'party_export',
      'fin_view_overview', 'fin_view_transactions', 'fin_create_transactions', 'fin_manage_expenses', 'fin_manage_payments',
      'hrm_view_employees', 'hrm_manage_attendance', 'hrm_manage_leave',
      'rep_view_sales', 'rep_view_purchase', 'rep_view_inventory', 'rep_download_pdf',
      'quote_view', 'quote_create', 'quote_edit', 'quote_approve', 'quote_convert',
      'set_view_profile',
    ],
  },
  {
    id: 'role-sales-person',
    name: 'Sales Person / Cashier',
    nameBn: 'বিক্রয়কর্মী / ক্যাশিয়ার',
    description: 'Point of sale billing, customer lookup, and basic invoice generation with guardrails.',
    descriptionBn: 'পিওএস কাউন্টারে দ্রুত বিক্রয় বিলিং ও কাস্টমার লেজার দেখার অনুমতি।',
    isSystemProtected: true,
    color: '#10b981',
    defaultDataScope: 'own_records',
    defaultBranchMode: 'selected',
    permissionIds: [
      'dash_view_overview',
      'sales_view', 'sales_create', 'sales_view_history',
      'party_view_customers', 'party_create_customer',
      'quote_view', 'quote_create',
    ],
  },
  {
    id: 'role-inventory-manager',
    name: 'Inventory & Store Officer',
    nameBn: 'ইনভেন্টরি ও স্টোর অফিসার',
    description: 'Warehouse goods receipt, item stock tracking, batch FEFO expiry management, and transfers.',
    descriptionBn: 'ওয়্যারহাউস স্টক ট্র্যাকিং, ব্যাচ ও মেয়াদ পরিচালনা এবং গুদাম স্থানান্তর।',
    isSystemProtected: true,
    color: '#f59e0b',
    defaultDataScope: 'assigned_branches',
    defaultBranchMode: 'selected',
    permissionIds: [
      'dash_view_overview',
      'pur_view', 'pur_view_history',
      'inv_view', 'inv_add_products', 'inv_edit_products', 'inv_transfer_stock', 'inv_view_alerts', 'inv_batches', 'inv_export',
      'rep_view_inventory', 'rep_download_pdf',
    ],
  },
  {
    id: 'role-accountant',
    name: 'Chief Accountant',
    nameBn: 'প্রধান হিসাবরক্ষক',
    description: 'Financial ledger maintenance, voucher posting, supplier payments, and profit & loss analysis.',
    descriptionBn: 'আর্থিক হিসাববিজ্ঞান, ভাউচার এন্ট্রি, পেমেন্ট ও লাভ-ক্ষতির অডিট প্রস্তুত।',
    isSystemProtected: true,
    color: '#6366f1',
    defaultDataScope: 'entire_business',
    defaultBranchMode: 'all',
    permissionIds: [
      'dash_view_overview', 'dash_view_summary', 'dash_export_kpi',
      'sales_view', 'sales_view_history', 'sales_export',
      'pur_view', 'pur_view_history', 'pur_export',
      'party_view_customers', 'party_view_suppliers', 'party_manage_credit_limits', 'party_view_transactions', 'party_export',
      'fin_view_overview', 'fin_view_transactions', 'fin_create_transactions', 'fin_edit_transactions', 'fin_manage_expenses', 'fin_manage_payments', 'fin_manage_banks', 'fin_view_reports', 'fin_export',
      'rep_view_sales', 'rep_view_purchase', 'rep_view_inventory', 'rep_view_financial', 'rep_export_excel', 'rep_download_pdf',
    ],
  },
  {
    id: 'role-hr-manager',
    name: 'HR & Admin Manager',
    nameBn: 'এইচআর ও অ্যাডমিন ম্যানেজার',
    description: 'Staff onboarding, attendance logging, leave sanctions, and monthly payroll calculation.',
    descriptionBn: 'কর্মী রিক্রুটমেন্ট, উপস্থিতি পর্যবেক্ষণ, ছুটি অনুমোদন এবং স্যালারি শিট প্রসেসিং।',
    isSystemProtected: false,
    color: '#ec4899',
    defaultDataScope: 'entire_business',
    defaultBranchMode: 'all',
    permissionIds: [
      'dash_view_overview',
      'hrm_view_employees', 'hrm_add_employees', 'hrm_edit_employees', 'hrm_manage_attendance', 'hrm_manage_leave', 'hrm_manage_payroll', 'hrm_view_reports', 'hrm_export',
      'rep_view_hr', 'rep_download_pdf',
    ],
  },
];

// ─── ROLE COLOR PRESETS ──────────────────────────────────────────────────────

export const ROLE_COLOR_PRESETS = [
  { name: 'Indigo', hex: '#6366f1' },
  { name: 'Blue', hex: '#3b82f6' },
  { name: 'Sky', hex: '#0ea5e9' },
  { name: 'Cyan', hex: '#06b6d4' },
  { name: 'Teal', hex: '#14b8a6' },
  { name: 'Emerald', hex: '#10b981' },
  { name: 'Amber', hex: '#f59e0b' },
  { name: 'Orange', hex: '#f97316' },
  { name: 'Rose', hex: '#f43f5e' },
  { name: 'Red', hex: '#ef4444' },
  { name: 'Pink', hex: '#ec4899' },
  { name: 'Purple', hex: '#8b5cf6' },
  { name: 'Violet', hex: '#7c3aed' },
  { name: 'Slate', hex: '#64748b' },
];

// ─── INITIAL USER ACCESS PROFILES (MOCK DATA) ────────────────────────────────

export const INITIAL_USER_PROFILES: UserAccessProfile[] = [
  {
    id: 'u-1',
    userId: 'usr-sweet-ali',
    employeeId: 'EMP-001',
    name: 'Sweet Ali',
    nameBn: 'সুইট আলী',
    email: 'sweet.ali@hellokhata.com',
    phone: '01711-001122',
    department: 'Management',
    designation: 'Business Owner & Founder',
    status: 'active',
    isOwner: true,
    isFullSystemAccess: true,
    baseRoleId: 'role-owner',
    accessLevel: 'full_system',
    branchScopeMode: 'all',
    allowedBranchIds: ['branch-1', 'branch-2', 'branch-3', 'branch-4', 'branch-5'],
    dataScope: 'entire_business',
    customGrantedPermissions: [],
    customRevokedPermissions: [],
    lastActive: 'Just now',
    updatedAt: '2026-09-14 10:30 AM',
    updatedBy: 'System SuperAdmin',
  },
  {
    id: 'u-2',
    userId: 'usr-mamun',
    employeeId: 'EMP-002',
    name: 'Mamunur Rashid',
    nameBn: 'মামুনুর রশীদ',
    email: 'mamun@hellokhata.com',
    phone: '01822-334455',
    department: 'Operations',
    designation: 'Dhaka Branch Manager',
    status: 'active',
    isOwner: false,
    isFullSystemAccess: false,
    baseRoleId: 'role-branch-manager',
    accessLevel: 'branch_restricted',
    branchScopeMode: 'selected',
    allowedBranchIds: ['branch-1'],
    dataScope: 'assigned_branches',
    customGrantedPermissions: ['sales_price_override', 'inv_manage_warehouses'],
    customRevokedPermissions: ['set_view_profile'],
    lastActive: '12 mins ago',
    updatedAt: '2026-09-12 04:15 PM',
    updatedBy: 'Sweet Ali',
  },
  {
    id: 'u-3',
    userId: 'usr-rahim',
    employeeId: 'EMP-003',
    name: 'Rahim Sheikh',
    nameBn: 'রহিম শেখ',
    email: 'rahim.sales@hellokhata.com',
    phone: '01933-445566',
    department: 'Sales',
    designation: 'Senior Sales Executive',
    status: 'active',
    isOwner: false,
    isFullSystemAccess: false,
    baseRoleId: 'role-sales-person',
    accessLevel: 'custom_access',
    branchScopeMode: 'selected',
    allowedBranchIds: ['branch-1'],
    dataScope: 'own_records',
    customGrantedPermissions: ['sales_process_return', 'sales_apply_discount'],
    customRevokedPermissions: ['quote_create'],
    lastActive: '3 mins ago',
    updatedAt: '2026-09-15 09:40 AM',
    updatedBy: 'Sweet Ali',
  },
  {
    id: 'u-4',
    userId: 'usr-farhana',
    employeeId: 'EMP-004',
    name: 'Farhana Akter',
    nameBn: 'ফারহানা আক্তার',
    email: 'farhana.acc@hellokhata.com',
    phone: '01844-556677',
    department: 'Accounts & Finance',
    designation: 'Head of Accounts',
    status: 'active',
    isOwner: false,
    isFullSystemAccess: false,
    baseRoleId: 'role-accountant',
    accessLevel: 'custom_access',
    branchScopeMode: 'all',
    allowedBranchIds: ['branch-1', 'branch-2', 'branch-3'],
    dataScope: 'entire_business',
    customGrantedPermissions: ['hrm_manage_payroll'],
    customRevokedPermissions: ['fin_manage_capital'],
    lastActive: '1 hour ago',
    updatedAt: '2026-09-10 11:20 AM',
    updatedBy: 'Sweet Ali',
  },
  {
    id: 'u-5',
    userId: 'usr-tariq',
    employeeId: 'EMP-005',
    name: 'Tariqul Islam',
    nameBn: 'তরিকুল ইসলাম',
    email: 'tariq.store@hellokhata.com',
    phone: '01755-667788',
    department: 'Warehouse',
    designation: 'Central Warehouse Keeper',
    status: 'active',
    isOwner: false,
    isFullSystemAccess: false,
    baseRoleId: 'role-inventory-manager',
    accessLevel: 'branch_restricted',
    branchScopeMode: 'selected',
    allowedBranchIds: ['branch-1', 'branch-2'],
    dataScope: 'assigned_branches',
    customGrantedPermissions: ['pur_create'],
    customRevokedPermissions: [],
    lastActive: 'Yesterday',
    updatedAt: '2026-09-08 02:00 PM',
    updatedBy: 'Mamunur Rashid',
  },
  {
    id: 'u-6',
    userId: 'usr-nasrin',
    employeeId: 'EMP-006',
    name: 'Nasrin Sultana',
    nameBn: 'নাসরিন সুলতানা',
    email: 'nasrin.hr@hellokhata.com',
    phone: '01666-778899',
    department: 'Human Resources',
    designation: 'HR Executive',
    status: 'active',
    isOwner: false,
    isFullSystemAccess: false,
    baseRoleId: 'role-hr-manager',
    accessLevel: 'restricted',
    branchScopeMode: 'all',
    allowedBranchIds: ['branch-1', 'branch-2', 'branch-3', 'branch-4', 'branch-5'],
    dataScope: 'entire_business',
    customGrantedPermissions: [],
    customRevokedPermissions: ['hrm_manage_payroll'],
    lastActive: '2 days ago',
    updatedAt: '2026-09-05 03:45 PM',
    updatedBy: 'Sweet Ali',
  },
];

// ─── INITIAL AUDIT LOGS ──────────────────────────────────────────────────────

export const INITIAL_AUDIT_LOGS: AccessAuditEntry[] = [
  {
    id: 'aud-101',
    timestamp: 'Today, 09:40 AM',
    performedBy: 'Sweet Ali (Owner)',
    targetUserName: 'Rahim Sheikh',
    targetUserRole: 'Sales Person',
    actionType: 'permission_override',
    addedPermissions: ['Sales → Process Sales Returns', 'Sales → Apply Discounts'],
    removedPermissions: ['Quotations → Create Quotation'],
    notes: 'Granted return and discount privileges for POS desk rush hour.',
  },
  {
    id: 'aud-102',
    timestamp: 'Yesterday, 04:15 PM',
    performedBy: 'Sweet Ali (Owner)',
    targetUserName: 'Mamunur Rashid',
    targetUserRole: 'Branch Manager',
    actionType: 'branch_scope_updated',
    addedPermissions: ['Sales → Override Unit Prices'],
    removedPermissions: ['Settings → View Business Settings'],
    branchChanges: { added: ['Dhaka Main Branch'], removed: ['Chittagong Branch'] },
    notes: 'Locked branch scope strictly to Dhaka Main Branch with price override ability.',
  },
  {
    id: 'aud-103',
    timestamp: '14 Sep, 10:30 AM',
    performedBy: 'System SuperAdmin',
    targetUserName: 'Sweet Ali',
    targetUserRole: 'Owner / Super Admin',
    actionType: 'full_access_granted',
    addedPermissions: ['All ERP Modules & Actions'],
    removedPermissions: [],
    notes: 'Primary enterprise organization initialized with Full System Access.',
  },
];
